language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libzmq-dev libblas-dev liblapack-dev libatlas-dev
install:
  - pip install -r requirements.txt 
  - pip install coveralls
script:
  - python setup.py test
  - python -m coverage run --source semlm setup.py test
after_success:
  - coveralls
